[general]
name = "evaluadorCV"

[cli]
hidedefaultmsg = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#31333F"
font = "Monospace"
